# Generated by Django 3.2.7 on 2022-07-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': '1. TO DO LIST',
            },
        ),
        migrations.CreateModel(
            name='ToDoListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist')),
            ],
            options={
                'verbose_name_plural': '2. TO DO LIST ITEMS',
            },
        ),
    ]
