# Generated by Django 3.2.7 on 2022-07-04 05:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitems',
            name='checked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='todolistitems',
            name='due_date',
            field=models.DateField(blank=True, default=main.models.one_week_hence, null=True),
        ),
    ]
