# Generated by Django 3.2.7 on 2022-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220704_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitems',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
