# Generated by Django 3.2.7 on 2022-07-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
